### ISSUE TITLE
djangocms_modules/base.html assumes "base.html" template to extend

### ISSUE THREAD

**Issue by bmcmurray** [divio/djangocms-modules#10]
The template `djangocms_modules/base.html` extends `base.html` which it assumes exists in a project but which may not.

**Comment by FinalAngel** [comment]
@bmcmurray thanks for hinting that out, I'll add an amendment to the README.

**Comment by jeroenpeters1986** [comment]
@FinalAngel I am not sure what I should be extending here. My website layout?
