### ISSUE TITLE
Permission Based Structure Changes in Modules

### ISSUE THREAD

**Issue by SteinRobert** [divio/djangocms-modules#5]
We'd like to extend the modules extension in the following way:

1. Implement a typical django permission which defines whether a user is allowed to change the structure of a module.
2. If a user is not allowed to change the structure of a module, we remove the css classes which make a plugin collapsible in the structure view e.g.: `.cms-dragitem-collapsable`. We might need a template tag to check the permission here.

This would make it possible for admin, superusers or sitebuilders to define well structured modules without allowing any other editor of the CMS to break out of the given structures. The editors are just allowed to change the content via double click and dragging the whole module to another place within the placeholder.

It would be nice if we could get some feedback on this @FinalAngel @czpython 

Do you think this is a suitable way to implement the asked requirements?

**Comment by vxsx** [comment]
Sounds good. Although I think keyboard shortcuts might still allow expanding / collapsing, but i'm not sure anymore.

**Comment by FinalAngel** [comment]
@SteinRobert are there still plans to add these changes from your end? Otherwise I'll close this for now :)

**Comment by SteinRobert** [comment]
Nope, we can close this.
