### ISSUE TITLE
Modules not shown in Add plugin to placeholder "Content"

### ISSUE THREAD

**Issue by rolandf** [divio/djangocms-modules#9]
I installed the djangocms_modules addon through pip install djangocms_modules, added it to INSTALLED_APPS migrated the db and collected static files. I can create modules, I can list them, I can copy and paste them but they are not displayed in the Add plugin box under the category I created. I can see this box in the Divio video announcing DjangoCms 3.6 and in Divio cloud with Django CMS 3.5.3. I'm on Djangocms 3.6. I' m using bootstrap4 plugin from divio.

Also in the add plugin, there is a module plugin that return a 403 forbiden but I'm the super user. Django Cms permissions are enabled.

**Comment by FinalAngel** [comment]
thank you for the feedback @rolandf, what Django version are you using?

**Comment by FinalAngel** [comment]
I can confirm that it is working on Divio Cloud using django CMS 3.6. How did you setup your Django project?

**Comment by FinalAngel** [comment]
@rolandf thanks for the info. I was able to reproduce the issue. You can solve it by adding 'djangocms_modules' **before** 'cms' in ``INSTALLED_APPS``.

I make sure to create a PR to the README
